name: Takoma Park NatureLab
pygments: true

prose:
  media: '/media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    cal:
      - name: "layout"
        field:
          element: "hidden"
          value: "cal"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add tags"
          placeholder: "Choose tags"
          options:
            - name: "Young Children"
              value: "young_children"
            - name: "Adults"
              value: "adults"
